#PROGRAM FOR RANDOM NUMBERS
#BY LALELANI EDDIE NENE
#MAM1043H-RANDOM NUMBERS

#PROGRAM THAT STIMULATES A COIN TOSS EXPERIMENT
import random


#VARIABLE WITH THE TWO POSSIBLE OUTCOMES

toss = random.randint(1,2)

#CONDITIONS FOR THE OUTPUT BASED ON THE TOSS VARIABLE OUTCOME
if toss==1 :
    print("heads")
if toss==2 :
    print("tails")